import { Recipe, RecipeDetail } from '../types/recipe';

// Indian Recipes Database with North Karnataka, South Indian, North Indian, and Punjabi cuisines
export const indianRecipes: RecipeDetail[] = [
  // North Karnataka Dishes
  {
    id: 'nk001',
    name: 'Jolada Rotti with Ennegayi',
    thumbnail: 'https://www.themealdb.com/images/media/meals/xxpqsy1511452222.jpg',
    category: 'North Karnataka',
    area: 'India',
    tags: ['North Karnataka', 'Traditional', 'Vegetarian'],
    instructions: '1. Make dough with jowar flour and warm water\n2. Roll into thick rotis on a wet cloth\n3. Cook on hot tawa until brown spots appear\n4. For Ennegayi: Stuff brinjals with spice mix of groundnut powder, coconut, red chili, coriander\n5. Cook stuffed brinjals in oil until tender\n6. Serve hot rotti with ennegayi and chutney powder',
    ingredients: [
      { ingredient: 'Jowar Flour', measure: '2 cups' },
      { ingredient: 'Water', measure: 'as needed' },
      { ingredient: 'Brinjal', measure: '6 medium' },
      { ingredient: 'Groundnut Powder', measure: '1/2 cup' },
      { ingredient: 'Coconut (grated)', measure: '1/4 cup' },
      { ingredient: 'Red Chili Powder', measure: '2 tsp' },
      { ingredient: 'Coriander Powder', measure: '1 tsp' },
      { ingredient: 'Oil', measure: '3 tbsp' },
      { ingredient: 'Salt', measure: 'to taste' },
    ],
  },
  {
    id: 'nk002',
    name: 'Badanekai Yennegai (Stuffed Brinjal)',
    thumbnail: 'https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg',
    category: 'North Karnataka',
    area: 'India',
    tags: ['North Karnataka', 'Spicy', 'Vegetarian'],
    instructions: '1. Make masala with roasted groundnuts, sesame, coconut, and spices\n2. Make slits in brinjals and stuff with masala\n3. Heat oil and add mustard seeds, curry leaves\n4. Add stuffed brinjals and cook covered on low flame\n5. Turn occasionally until brinjals are tender\n6. Serve with jowar rotti',
    ingredients: [
      { ingredient: 'Brinjal', measure: '500g' },
      { ingredient: 'Roasted Groundnuts', measure: '1/2 cup' },
      { ingredient: 'Sesame Seeds', measure: '2 tbsp' },
      { ingredient: 'Coconut (grated)', measure: '1/4 cup' },
      { ingredient: 'Red Chilies', measure: '6-8' },
      { ingredient: 'Tamarind', measure: '1 small ball' },
      { ingredient: 'Jaggery', measure: '1 tsp' },
      { ingredient: 'Mustard Seeds', measure: '1 tsp' },
      { ingredient: 'Curry Leaves', measure: '10-12' },
      { ingredient: 'Oil', measure: '4 tbsp' },
    ],
  },
  {
    id: 'nk003',
    name: 'Girmit (North Karnataka Style)',
    thumbnail: 'https://www.themealdb.com/images/media/meals/llcbn01574260722.jpg',
    category: 'North Karnataka',
    area: 'India',
    tags: ['Street Food', 'Spicy', 'Vegetarian'],
    instructions: '1. Soak puffed rice in water and drain well\n2. Mix with chopped onions, tomatoes, coriander\n3. Add lemon juice, chaat masala, red chili powder\n4. Mix in roasted groundnuts and sev\n5. Garnish with more sev and serve immediately',
    ingredients: [
      { ingredient: 'Puffed Rice', measure: '3 cups' },
      { ingredient: 'Onion (chopped)', measure: '1 large' },
      { ingredient: 'Tomato (chopped)', measure: '1 large' },
      { ingredient: 'Groundnuts (roasted)', measure: '1/2 cup' },
      { ingredient: 'Lemon', measure: '2' },
      { ingredient: 'Chaat Masala', measure: '1 tsp' },
      { ingredient: 'Red Chili Powder', measure: '1 tsp' },
      { ingredient: 'Coriander Leaves', measure: '2 tbsp' },
      { ingredient: 'Sev', measure: '1 cup' },
    ],
  },

  // South Indian Dishes
  {
    id: 'si001',
    name: 'Masala Dosa',
    thumbnail: 'https://www.themealdb.com/images/media/meals/g6qs6q1487351887.jpg',
    category: 'South Indian',
    area: 'India',
    tags: ['South Indian', 'Breakfast', 'Vegetarian'],
    instructions: '1. Prepare dosa batter by grinding rice and urad dal\n2. Ferment overnight\n3. For masala: Boil and mash potatoes\n4. Temper with mustard, curry leaves, onions, green chilies\n5. Add turmeric and mix with potatoes\n6. Spread dosa batter on hot tawa\n7. Add potato masala and fold\n8. Serve with coconut chutney and sambar',
    ingredients: [
      { ingredient: 'Rice', measure: '2 cups' },
      { ingredient: 'Urad Dal', measure: '1/2 cup' },
      { ingredient: 'Potatoes', measure: '4 large' },
      { ingredient: 'Onion', measure: '1 large' },
      { ingredient: 'Mustard Seeds', measure: '1 tsp' },
      { ingredient: 'Curry Leaves', measure: '10' },
      { ingredient: 'Green Chilies', measure: '3' },
      { ingredient: 'Turmeric Powder', measure: '1/2 tsp' },
      { ingredient: 'Oil', measure: 'as needed' },
    ],
  },
  {
    id: 'si002',
    name: 'Idli Sambar',
    thumbnail: 'https://www.themealdb.com/images/media/meals/mlchx21564916997.jpg',
    category: 'South Indian',
    area: 'India',
    tags: ['South Indian', 'Breakfast', 'Healthy'],
    instructions: '1. Prepare idli batter with rice and urad dal, ferment\n2. Pour in greased idli molds and steam for 10-12 minutes\n3. For sambar: Cook toor dal with vegetables\n4. Add tamarind extract and sambar powder\n5. Temper with mustard, curry leaves, hing\n6. Serve hot idlis with sambar and coconut chutney',
    ingredients: [
      { ingredient: 'Idli Rice', measure: '2 cups' },
      { ingredient: 'Urad Dal', measure: '1/2 cup' },
      { ingredient: 'Toor Dal', measure: '1 cup' },
      { ingredient: 'Vegetables (mixed)', measure: '2 cups' },
      { ingredient: 'Sambar Powder', measure: '2 tbsp' },
      { ingredient: 'Tamarind', measure: '1 lemon size' },
      { ingredient: 'Mustard Seeds', measure: '1 tsp' },
      { ingredient: 'Curry Leaves', measure: '12' },
      { ingredient: 'Hing (Asafoetida)', measure: '1/4 tsp' },
    ],
  },
  {
    id: 'si003',
    name: 'Bisi Bele Bath',
    thumbnail: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?w=500',
    category: 'South Indian',
    area: 'India',
    tags: ['South Indian', 'Rice', 'Spicy'],
    instructions: '1. Cook rice and toor dal together\n2. Roast spices and grind with coconut\n3. Cook vegetables with tamarind water\n4. Mix rice-dal, vegetables, and spice paste\n5. Temper with ghee, cashews, curry leaves\n6. Serve hot with papad and raita',
    ingredients: [
      { ingredient: 'Rice', measure: '1 cup' },
      { ingredient: 'Toor Dal', measure: '1/2 cup' },
      { ingredient: 'Mixed Vegetables', measure: '2 cups' },
      { ingredient: 'Tamarind', measure: '1 lemon size' },
      { ingredient: 'Bisi Bele Bath Powder', measure: '3 tbsp' },
      { ingredient: 'Ghee', measure: '3 tbsp' },
      { ingredient: 'Cashews', measure: '10' },
      { ingredient: 'Curry Leaves', measure: '15' },
    ],
  },

  // North Indian Dishes
  {
    id: 'ni001',
    name: 'Butter Chicken',
    thumbnail: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=500',
    category: 'North Indian',
    area: 'India',
    tags: ['North Indian', 'Chicken', 'Curry'],
    instructions: '1. Marinate chicken with yogurt, ginger-garlic paste, and spices\n2. Grill or pan-fry until cooked\n3. Make gravy with tomatoes, cashews, and cream\n4. Add butter and kasuri methi\n5. Add grilled chicken to gravy\n6. Simmer for 10 minutes\n7. Serve with naan or rice',
    ingredients: [
      { ingredient: 'Chicken', measure: '500g' },
      { ingredient: 'Yogurt', measure: '1/2 cup' },
      { ingredient: 'Tomatoes', measure: '4 large' },
      { ingredient: 'Cashews', measure: '1/4 cup' },
      { ingredient: 'Cream', measure: '1/2 cup' },
      { ingredient: 'Butter', measure: '4 tbsp' },
      { ingredient: 'Ginger-Garlic Paste', measure: '2 tbsp' },
      { ingredient: 'Kasuri Methi', measure: '1 tbsp' },
      { ingredient: 'Garam Masala', measure: '1 tsp' },
    ],
  },
  {
    id: 'ni002',
    name: 'Chole Bhature',
    thumbnail: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?w=500',
    category: 'North Indian',
    area: 'India',
    tags: ['North Indian', 'Street Food', 'Vegetarian'],
    instructions: '1. Soak chickpeas overnight and pressure cook\n2. Make gravy with onions, tomatoes, and spices\n3. Add cooked chickpeas and simmer\n4. For bhature: Make dough with maida, yogurt, and baking soda\n5. Let rest for 2 hours\n6. Roll and deep fry until puffed\n7. Serve hot chole with bhature and pickles',
    ingredients: [
      { ingredient: 'Chickpeas', measure: '2 cups' },
      { ingredient: 'Onions', measure: '2 large' },
      { ingredient: 'Tomatoes', measure: '3 large' },
      { ingredient: 'Chole Masala', measure: '2 tbsp' },
      { ingredient: 'Maida (All Purpose Flour)', measure: '2 cups' },
      { ingredient: 'Yogurt', measure: '1/4 cup' },
      { ingredient: 'Baking Soda', measure: '1/2 tsp' },
      { ingredient: 'Oil for frying', measure: 'as needed' },
    ],
  },
  {
    id: 'ni003',
    name: 'Paneer Tikka',
    thumbnail: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=500',
    category: 'North Indian',
    area: 'India',
    tags: ['North Indian', 'Starter', 'Vegetarian'],
    instructions: '1. Cut paneer and vegetables into cubes\n2. Marinate with yogurt, spices, and lemon juice\n3. Let rest for 30 minutes\n4. Thread on skewers alternating paneer and vegetables\n5. Grill or bake until charred\n6. Brush with butter\n7. Serve hot with mint chutney',
    ingredients: [
      { ingredient: 'Paneer', measure: '400g' },
      { ingredient: 'Bell Peppers', measure: '2' },
      { ingredient: 'Onion', measure: '2' },
      { ingredient: 'Yogurt', measure: '1 cup' },
      { ingredient: 'Ginger-Garlic Paste', measure: '2 tbsp' },
      { ingredient: 'Red Chili Powder', measure: '1 tsp' },
      { ingredient: 'Garam Masala', measure: '1 tsp' },
      { ingredient: 'Kasuri Methi', measure: '1 tbsp' },
      { ingredient: 'Lemon Juice', measure: '2 tbsp' },
    ],
  },

  // Punjabi Dishes
  {
    id: 'pb001',
    name: 'Sarson da Saag with Makki di Roti',
    thumbnail: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=500',
    category: 'Punjabi',
    area: 'India',
    tags: ['Punjabi', 'Traditional', 'Vegetarian'],
    instructions: '1. Cook mustard greens with spinach until soft\n2. Add ginger, garlic, and green chilies\n3. Blend coarsely\n4. Temper with ghee, onions, and spices\n5. For roti: Make dough with makki flour\n6. Roll thick rotis and cook on tawa\n7. Serve hot saag with makki roti and white butter',
    ingredients: [
      { ingredient: 'Mustard Greens', measure: '500g' },
      { ingredient: 'Spinach', measure: '200g' },
      { ingredient: 'Makki Flour (Corn)', measure: '2 cups' },
      { ingredient: 'Ginger', measure: '2 inch' },
      { ingredient: 'Garlic', measure: '8 cloves' },
      { ingredient: 'Green Chilies', measure: '4' },
      { ingredient: 'Ghee', measure: '4 tbsp' },
      { ingredient: 'Onion', measure: '1 large' },
      { ingredient: 'White Butter', measure: 'for serving' },
    ],
  },
  {
    id: 'pb002',
    name: 'Dal Makhani',
    thumbnail: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=500',
    category: 'Punjabi',
    area: 'India',
    tags: ['Punjabi', 'Dal', 'Creamy'],
    instructions: '1. Soak black urad dal and rajma overnight\n2. Pressure cook until very soft\n3. Temper with butter, cumin, and ginger-garlic\n4. Add tomato puree and spices\n5. Simmer on low heat for 1-2 hours\n6. Add cream and more butter\n7. Serve hot with naan or rice',
    ingredients: [
      { ingredient: 'Black Urad Dal', measure: '1 cup' },
      { ingredient: 'Rajma (Kidney Beans)', measure: '1/4 cup' },
      { ingredient: 'Butter', measure: '6 tbsp' },
      { ingredient: 'Tomato Puree', measure: '1 cup' },
      { ingredient: 'Cream', measure: '1/2 cup' },
      { ingredient: 'Ginger-Garlic Paste', measure: '2 tbsp' },
      { ingredient: 'Cumin Seeds', measure: '1 tsp' },
      { ingredient: 'Garam Masala', measure: '1 tsp' },
      { ingredient: 'Kasuri Methi', measure: '2 tbsp' },
    ],
  },
  {
    id: 'pb003',
    name: 'Amritsari Kulcha',
    thumbnail: 'https://www.themealdb.com/images/media/meals/1550441882.jpg',
    category: 'Punjabi',
    area: 'India',
    tags: ['Punjabi', 'Bread', 'Stuffed'],
    instructions: '1. Make soft dough with maida, yogurt, and yeast\n2. Let rest for 2 hours\n3. Make filling with mashed potatoes, onions, and spices\n4. Stuff dough balls with filling\n5. Roll out and cook on tawa with ghee\n6. Press with cloth to make layers\n7. Serve hot with chole and pickles',
    ingredients: [
      { ingredient: 'Maida', measure: '2 cups' },
      { ingredient: 'Yogurt', measure: '1/4 cup' },
      { ingredient: 'Yeast', measure: '1 tsp' },
      { ingredient: 'Potatoes (boiled)', measure: '3' },
      { ingredient: 'Onion (chopped)', measure: '1' },
      { ingredient: 'Green Chilies', measure: '2' },
      { ingredient: 'Coriander Leaves', measure: '3 tbsp' },
      { ingredient: 'Amchur Powder', measure: '1 tsp' },
      { ingredient: 'Ghee', measure: 'as needed' },
    ],
  },
  {
    id: 'pb004',
    name: 'Punjabi Kadhi Pakora',
    thumbnail: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500',
    category: 'Punjabi',
    area: 'India',
    tags: ['Punjabi', 'Curry', 'Vegetarian'],
    instructions: '1. Make pakoras with besan, onions, and spices\n2. Deep fry until golden\n3. Make kadhi with yogurt, besan, and water\n4. Temper with ghee, cumin, and red chilies\n5. Add turmeric and simmer\n6. Add pakoras to kadhi\n7. Serve hot with rice',
    ingredients: [
      { ingredient: 'Yogurt', measure: '2 cups' },
      { ingredient: 'Besan (Gram Flour)', measure: '1/2 cup' },
      { ingredient: 'Onion', measure: '2' },
      { ingredient: 'Cumin Seeds', measure: '1 tsp' },
      { ingredient: 'Turmeric Powder', measure: '1/2 tsp' },
      { ingredient: 'Red Chili Powder', measure: '1 tsp' },
      { ingredient: 'Ghee', measure: '3 tbsp' },
      { ingredient: 'Curry Leaves', measure: '10' },
      { ingredient: 'Oil for frying', measure: 'as needed' },
    ],
  },

  // More North Karnataka Dishes
  {
    id: 'nk004',
    name: 'Ragi Mudde (Finger Millet Balls)',
    thumbnail: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=500',
    category: 'North Karnataka',
    area: 'India',
    tags: ['North Karnataka', 'Healthy', 'Traditional'],
    instructions: '1. Boil water with salt\n2. Add ragi flour gradually while stirring continuously\n3. Cook on low heat, stirring to avoid lumps\n4. Add little water and cook until soft\n5. Shape into balls while hot\n6. Serve with spicy sambar or soppu saaru (greens curry)',
    ingredients: [
      { ingredient: 'Ragi Flour (Finger Millet)', measure: '2 cups' },
      { ingredient: 'Water', measure: '4 cups' },
      { ingredient: 'Salt', measure: 'to taste' },
    ],
  },
  {
    id: 'nk005',
    name: 'Jhunka (Besan Curry)',
    thumbnail: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=500',
    category: 'North Karnataka',
    area: 'India',
    tags: ['North Karnataka', 'Quick', 'Vegetarian'],
    instructions: '1. Heat oil, add mustard seeds, curry leaves\n2. Add onions, green chilies, and sauté\n3. Add besan (gram flour) and roast well\n4. Add water gradually to avoid lumps\n5. Add turmeric, red chili powder\n6. Cook until thick and oil separates\n7. Serve with bhakri or jowar rotti',
    ingredients: [
      { ingredient: 'Besan (Gram Flour)', measure: '1 cup' },
      { ingredient: 'Onion (chopped)', measure: '1 large' },
      { ingredient: 'Green Chilies', measure: '3-4' },
      { ingredient: 'Mustard Seeds', measure: '1 tsp' },
      { ingredient: 'Curry Leaves', measure: '10' },
      { ingredient: 'Turmeric Powder', measure: '1/2 tsp' },
      { ingredient: 'Red Chili Powder', measure: '1 tsp' },
      { ingredient: 'Oil', measure: '3 tbsp' },
    ],
  },
  {
    id: 'nk006',
    name: 'Dharwad Peda',
    thumbnail: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500',
    category: 'North Karnataka',
    area: 'India',
    tags: ['North Karnataka', 'Sweet', 'Dessert'],
    instructions: '1. Boil milk until reduced to half\n2. Add sugar and cardamom powder\n3. Keep stirring until thick and starts leaving sides\n4. Add ghee for shine\n5. Pour into greased plate\n6. Cut into diamond shapes when slightly cool\n7. Garnish with pistachios',
    ingredients: [
      { ingredient: 'Full Cream Milk', measure: '2 liters' },
      { ingredient: 'Sugar', measure: '1 cup' },
      { ingredient: 'Cardamom Powder', measure: '1 tsp' },
      { ingredient: 'Ghee', measure: '2 tbsp' },
      { ingredient: 'Pistachios (chopped)', measure: 'for garnish' },
    ],
  },

  // More South Indian Dishes
  {
    id: 'si004',
    name: 'Medu Vada',
    thumbnail: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=500',
    category: 'South Indian',
    area: 'India',
    tags: ['South Indian', 'Breakfast', 'Crispy'],
    instructions: '1. Soak urad dal for 3-4 hours\n2. Grind to fluffy batter without water\n3. Add chopped onions, curry leaves, ginger, chilies\n4. Season with salt and pepper\n5. Shape into donuts and deep fry\n6. Fry until golden and crispy\n7. Serve with coconut chutney and sambar',
    ingredients: [
      { ingredient: 'Urad Dal', measure: '2 cups' },
      { ingredient: 'Onion (chopped)', measure: '1' },
      { ingredient: 'Ginger (chopped)', measure: '1 tsp' },
      { ingredient: 'Green Chilies', measure: '3' },
      { ingredient: 'Curry Leaves', measure: '15' },
      { ingredient: 'Black Pepper', measure: '1 tsp' },
      { ingredient: 'Oil for frying', measure: 'as needed' },
      { ingredient: 'Salt', measure: 'to taste' },
    ],
  },
  {
    id: 'si005',
    name: 'Pongal',
    thumbnail: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?w=500',
    category: 'South Indian',
    area: 'India',
    tags: ['South Indian', 'Breakfast', 'Comfort Food'],
    instructions: '1. Dry roast moong dal until aromatic\n2. Pressure cook rice and dal with water\n3. Heat ghee, add cumin, pepper, ginger\n4. Add cashews and curry leaves\n5. Mix with cooked rice-dal mixture\n6. Add more ghee for richness\n7. Serve hot with coconut chutney',
    ingredients: [
      { ingredient: 'Rice', measure: '1 cup' },
      { ingredient: 'Moong Dal', measure: '1/2 cup' },
      { ingredient: 'Ghee', measure: '4 tbsp' },
      { ingredient: 'Cumin Seeds', measure: '1 tsp' },
      { ingredient: 'Black Pepper', measure: '1 tsp crushed' },
      { ingredient: 'Ginger (chopped)', measure: '1 tbsp' },
      { ingredient: 'Cashews', measure: '15' },
      { ingredient: 'Curry Leaves', measure: '20' },
    ],
  },
  {
    id: 'si006',
    name: 'Rasam',
    thumbnail: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=500',
    category: 'South Indian',
    area: 'India',
    tags: ['South Indian', 'Soup', 'Spicy'],
    instructions: '1. Cook toor dal until soft\n2. Extract tamarind juice\n3. Crush pepper, cumin, and garlic\n4. Boil tamarind water with tomatoes\n5. Add rasam powder and dal water\n6. Temper with mustard, curry leaves in ghee\n7. Serve hot as soup or with rice',
    ingredients: [
      { ingredient: 'Toor Dal', measure: '1/2 cup' },
      { ingredient: 'Tamarind', measure: '1 lemon size' },
      { ingredient: 'Tomatoes', measure: '2' },
      { ingredient: 'Rasam Powder', measure: '2 tbsp' },
      { ingredient: 'Black Pepper', measure: '1 tsp' },
      { ingredient: 'Cumin Seeds', measure: '1 tsp' },
      { ingredient: 'Garlic', measure: '4 cloves' },
      { ingredient: 'Curry Leaves', measure: '15' },
      { ingredient: 'Coriander Leaves', measure: '2 tbsp' },
    ],
  },
  {
    id: 'si007',
    name: 'Upma',
    thumbnail: 'https://images.unsplash.com/photo-1630383249896-424e482df921?w=500',
    category: 'South Indian',
    area: 'India',
    tags: ['South Indian', 'Breakfast', 'Quick'],
    instructions: '1. Dry roast rava until aromatic\n2. Heat oil, add mustard, urad dal, chana dal\n3. Add curry leaves, ginger, chilies\n4. Add onions and vegetables, sauté\n5. Add hot water (2:1 ratio)\n6. Add roasted rava gradually while stirring\n7. Cover and cook for 2 minutes, garnish with coriander',
    ingredients: [
      { ingredient: 'Rava (Semolina)', measure: '1 cup' },
      { ingredient: 'Water', measure: '2 cups' },
      { ingredient: 'Onion', measure: '1 large' },
      { ingredient: 'Mixed Vegetables', measure: '1 cup' },
      { ingredient: 'Mustard Seeds', measure: '1 tsp' },
      { ingredient: 'Urad Dal', measure: '1 tsp' },
      { ingredient: 'Chana Dal', measure: '1 tsp' },
      { ingredient: 'Green Chilies', measure: '3' },
      { ingredient: 'Curry Leaves', measure: '15' },
      { ingredient: 'Ginger (chopped)', measure: '1 tsp' },
    ],
  },

  // More North Indian Dishes
  {
    id: 'ni004',
    name: 'Rajma Masala (Kidney Bean Curry)',
    thumbnail: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=500',
    category: 'North Indian',
    area: 'India',
    tags: ['North Indian', 'Curry', 'Protein Rich'],
    instructions: '1. Soak rajma overnight and pressure cook until soft\n2. Make onion-tomato gravy with ginger-garlic\n3. Add red chili powder, coriander powder, garam masala\n4. Add boiled rajma with some water\n5. Mash few beans for thick gravy\n6. Simmer for 15 minutes\n7. Garnish with coriander, serve with rice',
    ingredients: [
      { ingredient: 'Rajma (Kidney Beans)', measure: '2 cups' },
      { ingredient: 'Onions', measure: '2 large' },
      { ingredient: 'Tomatoes', measure: '3 large' },
      { ingredient: 'Ginger-Garlic Paste', measure: '2 tbsp' },
      { ingredient: 'Red Chili Powder', measure: '1 tsp' },
      { ingredient: 'Coriander Powder', measure: '2 tsp' },
      { ingredient: 'Garam Masala', measure: '1 tsp' },
      { ingredient: 'Oil', measure: '3 tbsp' },
      { ingredient: 'Coriander Leaves', measure: '3 tbsp' },
    ],
  },
  {
    id: 'ni005',
    name: 'Aloo Paratha',
    thumbnail: 'https://www.themealdb.com/images/media/meals/58oia61564916529.jpg',
    category: 'North Indian',
    area: 'India',
    tags: ['North Indian', 'Breakfast', 'Stuffed Bread'],
    instructions: '1. Make dough with wheat flour, salt, and water\n2. Boil and mash potatoes\n3. Mix with onions, chilies, coriander, spices\n4. Make balls of dough and filling\n5. Stuff and roll out carefully\n6. Cook on tawa with ghee until golden spots\n7. Serve with yogurt, pickle, and butter',
    ingredients: [
      { ingredient: 'Wheat Flour', measure: '2 cups' },
      { ingredient: 'Potatoes (boiled)', measure: '4 large' },
      { ingredient: 'Onion (chopped)', measure: '1' },
      { ingredient: 'Green Chilies', measure: '2' },
      { ingredient: 'Coriander Leaves', measure: '3 tbsp' },
      { ingredient: 'Red Chili Powder', measure: '1/2 tsp' },
      { ingredient: 'Amchur Powder', measure: '1 tsp' },
      { ingredient: 'Ghee', measure: 'as needed' },
    ],
  },
  {
    id: 'ni006',
    name: 'Palak Paneer',
    thumbnail: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500',
    category: 'North Indian',
    area: 'India',
    tags: ['North Indian', 'Curry', 'Healthy'],
    instructions: '1. Blanch spinach and puree\n2. Fry paneer cubes until golden\n3. Temper with cumin, onions, ginger-garlic\n4. Add tomatoes and cook until soft\n5. Add spices and spinach puree\n6. Add cream and paneer\n7. Simmer for 5 minutes, serve with naan',
    ingredients: [
      { ingredient: 'Spinach (Palak)', measure: '500g' },
      { ingredient: 'Paneer', measure: '300g' },
      { ingredient: 'Onions', measure: '2' },
      { ingredient: 'Tomatoes', measure: '2' },
      { ingredient: 'Cream', measure: '1/4 cup' },
      { ingredient: 'Ginger-Garlic Paste', measure: '1 tbsp' },
      { ingredient: 'Cumin Seeds', measure: '1 tsp' },
      { ingredient: 'Garam Masala', measure: '1 tsp' },
      { ingredient: 'Kasuri Methi', measure: '1 tsp' },
    ],
  },

  // More Punjabi Dishes
  {
    id: 'pb005',
    name: 'Aloo Gobi (Potato Cauliflower Curry)',
    thumbnail: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=500',
    category: 'Punjabi',
    area: 'India',
    tags: ['Punjabi', 'Vegetarian', 'Dry Curry'],
    instructions: '1. Heat oil, add cumin seeds\n2. Add ginger, green chilies\n3. Add potatoes and cauliflower florets\n4. Add turmeric, red chili, coriander powder\n5. Cover and cook on low heat\n6. Stir occasionally until vegetables are tender\n7. Garnish with coriander leaves',
    ingredients: [
      { ingredient: 'Potatoes', measure: '3 medium' },
      { ingredient: 'Cauliflower', measure: '1 medium head' },
      { ingredient: 'Cumin Seeds', measure: '1 tsp' },
      { ingredient: 'Ginger (chopped)', measure: '1 tbsp' },
      { ingredient: 'Green Chilies', measure: '2' },
      { ingredient: 'Turmeric Powder', measure: '1/2 tsp' },
      { ingredient: 'Red Chili Powder', measure: '1 tsp' },
      { ingredient: 'Coriander Powder', measure: '1 tsp' },
      { ingredient: 'Coriander Leaves', measure: '2 tbsp' },
    ],
  },
  {
    id: 'pb006',
    name: 'Lassi (Yogurt Drink)',
    thumbnail: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=500',
    category: 'Punjabi',
    area: 'India',
    tags: ['Punjabi', 'Beverage', 'Refreshing'],
    instructions: '1. Blend yogurt with water and sugar\n2. Add cardamom powder\n3. Blend until frothy\n4. Add ice cubes\n5. Pour in glasses\n6. Top with cream (malai)\n7. Garnish with pistachios and rose petals',
    ingredients: [
      { ingredient: 'Fresh Yogurt', measure: '2 cups' },
      { ingredient: 'Water', measure: '1 cup' },
      { ingredient: 'Sugar', measure: '3 tbsp' },
      { ingredient: 'Cardamom Powder', measure: '1/4 tsp' },
      { ingredient: 'Ice cubes', measure: 'as needed' },
      { ingredient: 'Cream', measure: '2 tbsp' },
      { ingredient: 'Pistachios (chopped)', measure: 'for garnish' },
    ],
  },
  {
    id: 'pb007',
    name: 'Paneer Bhurji',
    thumbnail: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500',
    category: 'Punjabi',
    area: 'India',
    tags: ['Punjabi', 'Quick', 'Protein Rich'],
    instructions: '1. Crumble paneer into small pieces\n2. Heat oil, add cumin seeds\n3. Add onions, ginger, chilies, sauté\n4. Add tomatoes and cook until soft\n5. Add crumbled paneer and spices\n6. Mix well and cook for 5 minutes\n7. Garnish with coriander, serve with roti',
    ingredients: [
      { ingredient: 'Paneer', measure: '400g' },
      { ingredient: 'Onions', measure: '2 large' },
      { ingredient: 'Tomatoes', measure: '2 large' },
      { ingredient: 'Green Chilies', measure: '3' },
      { ingredient: 'Ginger (chopped)', measure: '1 tbsp' },
      { ingredient: 'Turmeric Powder', measure: '1/2 tsp' },
      { ingredient: 'Red Chili Powder', measure: '1 tsp' },
      { ingredient: 'Garam Masala', measure: '1 tsp' },
      { ingredient: 'Coriander Leaves', measure: '3 tbsp' },
    ],
  },
];

// Helper function to get all Indian recipes
export const getAllIndianRecipes = (): Recipe[] => {
  return indianRecipes.map(recipe => ({
    id: recipe.id,
    name: recipe.name,
    thumbnail: recipe.thumbnail,
    category: recipe.category,
    area: recipe.area,
    tags: recipe.tags,
  }));
};

// Helper function to get recipe by ID
export const getIndianRecipeById = (id: string): RecipeDetail | null => {
  return indianRecipes.find(recipe => recipe.id === id) || null;
};

// Helper function to get recipes by category
export const getIndianRecipesByCategory = (category: string): Recipe[] => {
  const filtered = indianRecipes.filter(recipe => recipe.category === category);
  return filtered.map(recipe => ({
    id: recipe.id,
    name: recipe.name,
    thumbnail: recipe.thumbnail,
    category: recipe.category,
    area: recipe.area,
    tags: recipe.tags,
  }));
};

// Helper function to search Indian recipes
export const searchIndianRecipes = (query: string): Recipe[] => {
  const lowerQuery = query.toLowerCase();
  const filtered = indianRecipes.filter(recipe => 
    recipe.name.toLowerCase().includes(lowerQuery) ||
    recipe.category.toLowerCase().includes(lowerQuery) ||
    recipe.tags.some(tag => tag.toLowerCase().includes(lowerQuery))
  );
  return filtered.map(recipe => ({
    id: recipe.id,
    name: recipe.name,
    thumbnail: recipe.thumbnail,
    category: recipe.category,
    area: recipe.area,
    tags: recipe.tags,
  }));
};
